name             'java_wrapper'
maintainer       'okram999'
maintainer_email 'nirish.okram@gmail.com'
license          'All rights reserved'
description      'Installs/Configures java'
long_description 'Installs/Configures java'
version          '0.1.0'
